apiVersion: v1
kind: Service
metadata:
    name: departamento
    labels:
        name: departamento
spec:
    type: NodePort
    ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP
    selector:
        app: departamento